steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/solutionsarchitect-01/incremental-rebalancing-producer-app', '.' ]
images:
- 'gcr.io/solutionsarchitect-01/incremental-rebalancing-producer-app'
