apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: incremental-rebalancing-producer-app
  name: incremental-rebalancing-producer-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incremental-rebalancing-producer-app
  template:
    metadata:
      labels:
        app: incremental-rebalancing-producer-app
    spec:
      containers:
      - name: incremental-rebalancing-producer-app
        image: gcr.io/solutionsarchitect-01/incremental-rebalancing-producer-app
        env:
        - name: PRODUCER_NUM_MESSAGES
          value: "500"
        - name: PRODUCER_FIXED_DELAY_MS
          value: "10"
        - name: PRODUCER_PAYLOAD_CHARACTERS
          value: "5000"
        resources: 
          requests: 
            memory: "100m"
            cpu: "100m"
          limits:
            memory: "250m"
            cpu: "250m"

