apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: incremental-rebalancing-consumer
  name: incremental-rebalancing-consumer
  namespace: default
spec:
  replicas: 302
  selector:
    matchLabels:
      app: incremental-rebalancing-consumer
  template:
    metadata:
      labels:
        app: incremental-rebalancing-consumer
    spec:
      containers:
      - name: incremental-rebalancing-consumer
        image: gcr.io/solutionsarchitect-01/incremental-rebalancing-consumer
        env:
        - name: MESSAGE_CONSUME_DELAY_MS
          value: "12"
        resources:
          requests:
            memory: "200m"
            cpu: "250m"
          limits:
            memory: "500m"
            cpu: "500m"

